### ISSUE TITLE
Legal/Lawyers: Add links to PDFs in Related Content Sections

### ISSUE THREAD

**Issue by chrisdaaz** [nulib/florence-kelley#10]
In `/content/legal/lawyers/`, the markdown files contain missing front-matter `url` values in the `related_content` sections. Here's an example:

```
---
title: "Vickers, Alonzo K."
image_file: site/i19989thmb.jpg
image_caption: "8 hour strike Chicago Typographical Union #16."
related_content:
  - title: "A History of Chicago (Vol. 3: The Rise of a Modern City, 1871-1893)"
    url:
  - title: "A History of the City of Chicago Its Men and Institutions: Biographical Sketches of Leading Citizens"
    url:
  - title: "Centennial History of the City of Chicago: Its Men and Institutions"
    url:
  - title: "Moran's Dictionary of Chicago and Its Vicinity"
    url:
  - title: "Politics and Politicians of Chicago, Cook County, and Illinois 1787-1887"
    url:
---
```
The urls refer to PDF documents in the [fk_documents folder](https://northwestern.box.com/s/mwg89ekzdxspt5ju6di4qn6j4jvxcgin) on Box.

Use the [fk_documents](https://northwestern.box.com/s/d5w8g37kde5w07nfwy0qf6h1ayghcwff) spreadsheet to search for the `title` of a document whose `url` is missing, add the `filename` to the `url` field, and append `.pdf` to the `filename` for every missing `url` field. 

Sometimes the value of the `title` field for the document does not exactly match the title of the PDF document in the spreadsheet. If you can't find the `filename` for the title of the in the `fk_documents` spreadsheet on Box, refer to the page on the current website ([http://florencekelley.northwestern.edu/](http://florencekelley.northwestern.edu/)] and use the same method you did for finding the image filename (via the Inspect Element > Network tab in devtools) in order to find the filename for the PDF document.

You can see this [previous commit](https://github.com/nulib/florence-kelley/commit/44eed572802b893a48e71a9bfe672f8dc2076b3f) as an example of what the finished markdown files should look like.

The scope of this issue is for all of the `.md` files in  `/content/legal/lawyers/`. If you have any questions that come up while working on this ticket, add a comment to this issue with a reference to the page you're having trouble with and leave a description of what's happening.

### Done looks like
- a PR is submitted with the missing url values
- if any of the files are missing `url` values, that's OK. just make a note in the PR description of which files are missing `url` values so I can address them late.
