### ISSUE TITLE
Create Related Content Links

### ISSUE THREAD

**Issue by chrisdaaz** [nulib/florence-kelley#5]
Most if not all of the static pages of the website contain a list of "Related Content" links in the right sidebar:

![image](https://user-images.githubusercontent.com/24395592/58043904-0e35c000-7b04-11e9-9979-a4fd04d46fe2.png)

These links need to be added to the page's front-matter YAML. For example, at the top of [`content/florence/education`](https://github.com/nulib/florence-kelley/blob/master/content/florence/education.md), there's an entry for `related_education` followed by `title` and `url` for each link.

```
related_content:
  - title: "Abolition of Slavery"
    url:
  - title: "Courts of Appeals"
    url:
  - title: "Feed for the Lawyers"
    url:
  - title: "Florence Kelley to Mary Thorn Lewis, June 10, 1885"
    url:
  - title: "Letters from Europe"
    url:
  - title: "On Some Changes in the Legal Status of the Child Since Blackstone"
    url:
  - title: "Sage Maidens of Cornell University"
    url:
  - title: "Sister Carrie"
    url:
```

For each link, the `title` and `url` values will be mapped to HTML:

```
<li><a href="{{ .url}} ">{{ .title }}</a></li>
```

For now, just focus on the titles. The URLs will be tricky.

### Done looks like

- [ ] `related_content` entries are added to the YAML front-matter for every page on http://florencekelley.northwestern.edu that has links these links in the sidebar.
